name: 'Deploy Birthday App'

on:
  push:
    branches: [ "main" ]
    paths:
    - 'helm/**'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Deploy Birthday App'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Kubectl and get context
      run: |
        curl -LO https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client
        aws eks update-kubeconfig --region us-east-1 --name testcluster
        kubectl get namespace

    - name: helm install app
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm version
        cd helm; helm upgrade --install birthdayapp ./birthdayapp/ -f birthdayapp/values.yaml
        kubectl apply -f ingress.yaml