name: 'Deploy Btc and API App'

on:
  push:
    branches: [ "main" ]
    paths:
    - 'helm/**'
  workflow_dispatch:

jobs:
  terraform:
    name: 'Deploy Btc and API App'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Kubectl and get context
      run: |
        curl -LO https://dl.k8s.io/release/v1.23.6/bin/linux/amd64/kubectl
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client
        aws eks update-kubeconfig --region us-east-1 --name myEksCluster
        kubectl get namespace

    - name: helm install
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm version

    - name: helm install ingress gateway
      run: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        pwd
        helm install gateway ingress-nginx/ingress-nginx \
        --namespace gateway \
        --set controller.metrics.enabled=true \
        --set-string controller.metrics.service.annotations."prometheus\.io/port"="10254" \
        --set-string controller.metrics.service.annotations."prometheus\.io/scrape"="true"

    - name: helm install btc
      run: |
        helm upgrade --install serviceB ./serviceB/ -f serviceB/values.yaml

    - name: helm install api
      run: |
        helm upgrade --install serviceB ./serviceB/ -f serviceB/values.yaml
        kubectl apply -f ingress.yaml