# .github/workflows/workflow-1.yml
name: Workflow 1

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - dev-blackcloak-customer-exp
          - qa-blackcloak-customer-exp
          - stg-blackcloak-customer-exp
      tag:
        description: Tag Used for docker image
        required: true
  
jobs:
  initial_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perform some tasks
        run: echo "Running Workflow 1..."

      # Trigger Workflow 1
      - name: Trigger Workflow 2
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            https://api.github.com/repos/dinusebastianbalan/aws-app/dispatches \
            -d '{"event_type":"trigger-action", "client_payload": {"env": "${{ github.event.inputs.environment }}", "tag": "${{ github.event.inputs.tag }}"}}'
